# Continuous Integration config
# travis-ci.org
#
# see http://about.travis-ci.org/docs/user/build-configuration/
#

language: python
sudo: false
cache:
  - pip

python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

env:
  - TOXENV=py3

matrix:
  include:
    - env: TOXENV=isort
    - env: TOXENV=codestyle
    - env: TOXENV=docstyle
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
  fast_finish: true

install:
  - pip install --upgrade pip tox

before_script:
  - echo $TOXENV

script: tox -e $TOXENV
