# Continuous Integration config
# travis-ci.org
#
# see http://about.travis-ci.org/docs/user/build-configuration/
#

language: python

python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

install:
  - pip install -r requirments-test.txt

script: pytest --cov --verbose
